version: '3'
services:
    webserver:
        container_name: jcpm-marketplace-webserver
        restart: unless-stopped
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php
        networks:
            - jcpm-marketplace-network

    php:
        container_name: jcpm-marketplace-php
        restart: unless-stopped
        build:
            context: ./php
            args:
                - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
            dockerfile: Dockerfile
        expose:
            - "9000"    
        volumes:
            - ${APPLICATION}:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - jcpm-marketplace-network

    mysql:
        container_name: jcpm-markerplace-mysql
        restart: unless-stopped
        build:
            context: ./mysql
            dockerfile: Dockerfile
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - jcpm-marketplace-network

    # elastic:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    #     container_name: jcpm-markerplace-elastic
    #     environment:
    #         - node.name=elastic
    #         - discovery.type=single-node
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     volumes:
    #         - ./elastic/data:/usr/share/elasticsearch/data
    #     ports:
    #         - "${ELASTIC_PORT}:9200"
    #     networks:
    #         - jcpm-marketplace-network

networks:
    jcpm-marketplace-network:
        driver: bridge